ALTER TABLE "PayoutWebhookEvent" ADD COLUMN IF NOT EXISTS "outcome" TEXT NOT NULL DEFAULT 'processed';
ALTER TABLE "PayoutWebhookEvent" ADD COLUMN IF NOT EXISTS "rawHash" TEXT NOT NULL DEFAULT '';
ALTER TABLE "PayoutWebhookEvent" ADD COLUMN IF NOT EXISTS "occurredAt" TIMESTAMP(3);
